### ISSUE TITLE
[Feature Request] - Desktop capture.

### ISSUE THREAD

**Issue by bitbound** [microsoft/winrtc#94] opened 2020-11-04 19:11 UTC
**Is your feature request related to a problem? Please describe.**
I'm the creator of a open-source remote support solution:  https://github.com/lucent-sea/Remotely

For remote control on the Windows agent, I'm using MixedReality WebRTC's external video source to stream the desktop (in combination with SharpDX to capture the frames).  It'd be nice to have desktop capture included in the WinRTC API, which I'd use to replace MR WebRTC.

**Describe the solution you'd like**
The ideal solution would look similar to how Electron does it:  https://www.electronjs.org/docs/api/desktop-capturer

There'd be an API to enumerate display devices and to return a video stream of a specified display, then add it as a track to the peer connection.

**Describe alternatives you've considered**
I'm currently using MixedReality.WebRTC's ExternalVideoTrackSource and SharpDX.

**Additional context**

**Comment by FrayxRulez** [comment] 2020-11-22 19:55
Duplicate of #91?

**Comment by lucent-sea** [comment] 2020-11-25 23:54
> File a new issue! Tell us what problem you're trying to solve, how you've tried to solve it so far, and what would be the ideal solution for your app. Bonus points if there's a gist or existing repo we can look at with you.

The above is from this repo's readme.  Since #91 doesn't include those elements for which they're asking, I wouldn't consider it a duplicate.

I'd also expect that screen capture would work for any Windows desktop app, not just UWP.

**Closed as completed** 2020-12-20 08:24 UTC
